name: Build and Run

on:
  push:
    branches:
      - '*'

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: build
        run: make
      - name: run
        run: make run

